
select jsonb_array_elements(Students) ->> 'AddressBlock' as AddressBlock,
       jsonb_array_elements(Students) ->> 'AdmissionNo' as AdmissionNo,
       jsonb_array_elements(Students) ->> 'Apartment' as Apartment,
       jsonb_array_elements(Students) ->> 'AsylumStatus' as AsylumStatus,
       jsonb_array_elements(Students) ->> 'Boarder' as Boarder,
       jsonb_array_elements(Students) ->> 'BoardingHouse' as BoardingHouse,
       jsonb_array_elements(Students) ->> 'Country' as Country,
       jsonb_array_elements(Students) ->> 'County' as County,
       jsonb_array_elements(Students) ->> 'DateofBirth' as DateofBirth,
       jsonb_array_elements(Students) ->> 'Destination' as Destination,
       jsonb_array_elements(Students) ->> 'DestinationStartDate' as DestinationStartDate,
       jsonb_array_elements(Students) ->> 'DisplayName' as DisplayName,
       jsonb_array_elements(Students) ->> 'District' as District,
       jsonb_array_elements(Students) ->> 'EAL' as EAL,
       jsonb_array_elements(Students) ->> 'EnglishProficiencyLevel' as EnglishProficiencyLevel,
       jsonb_array_elements(Students) ->> 'EnrolmentStatus' as EnrolmentStatus,
       jsonb_array_elements(Students) ->> 'EntryDate' as EntryDate,
       jsonb_array_elements(Students) ->> 'Ethnicity' as Ethnicity,
       jsonb_array_elements(Students) ->> 'EthnicityCode' as EthnicityCode,
       jsonb_array_elements(Students) ->> 'EthnicitySource' as EthnicitySource,
       jsonb_array_elements(Students) ->> 'EverInCare' as EverInCare,
       jsonb_array_elements(Students) ->> 'ExternalId' as ExternalId,
       jsonb_array_elements(Students) ->> 'FSMEver6' as FSMEver6,
       jsonb_array_elements(Students) ->> 'FirstLanguage' as FirstLanguage,
       jsonb_array_elements(Students) ->> 'FirstLanguageCode' as FirstLanguageCode,
       jsonb_array_elements(Students) ->> 'FirstLanguageSource' as FirstLanguageSource,
       jsonb_array_elements(Students) ->> 'Forename' as Forename,
       jsonb_array_elements(Students) ->> 'FsmEligible' as FsmEligible,
       jsonb_array_elements(Students) ->> 'FsmEndDate' as FsmEndDate,
       jsonb_array_elements(Students) ->> 'FsmStartDate' as FsmStartDate,
       jsonb_array_elements(Students) ->> 'Gender' as Gender,
       jsonb_array_elements(Students) ->> 'Gifted' as Gifted,
       jsonb_array_elements(Students) ->> 'HomeLanguage' as HomeLanguage,
       jsonb_array_elements(Students) ->> 'HomeLanguageCode' as HomeLanguageCode,
       jsonb_array_elements(Students) ->> 'HouseGroup' as HouseGroup,
       jsonb_array_elements(Students) ->> 'HouseGroupId' as HouseGroupId,
       jsonb_array_elements(Students) ->> 'HouseName' as HouseName,
       jsonb_array_elements(Students) ->> 'HouseNo' as HouseNo,
       jsonb_array_elements(Students) ->> 'Id' as Id,
       jsonb_array_elements(Students) ->> 'IdaasEmail' as IdaasEmail,
       jsonb_array_elements(Students) ->> 'IdaasId' as IdaasId,
       jsonb_array_elements(Students) ->> 'InLeaCare' as InLeaCare,
       jsonb_array_elements(Students) ->> 'IsTraveller' as IsTraveller,
       jsonb_array_elements(Students) ->> 'IsYoungCarer' as IsYoungCarer,
       jsonb_array_elements(Students) ->> 'KeyStage' as KeyStage,
       jsonb_array_elements(Students) ->> 'LastUpdated' as LastUpdated,
       jsonb_array_elements(Students) ->> 'LeaCareAuthority' as LeaCareAuthority,
       jsonb_array_elements(Students) ->> 'LeavingDate' as LeavingDate,
       jsonb_array_elements(Students) ->> 'LegalForename' as LegalForename,
       jsonb_array_elements(Students) ->> 'LegalSurname' as LegalSurname,
       jsonb_array_elements(Students) ->> 'MiddleName' as MiddleName,
       jsonb_array_elements(Students) ->> 'ModeOfTravel' as ModeOfTravel,
       jsonb_array_elements(Students) ->> 'NationalIdentity' as NationalIdentity,
       jsonb_array_elements(Students) ->> 'Nationality' as Nationality,
       jsonb_array_elements(Students) ->> 'OnReport' as OnReport,
       jsonb_array_elements(Students) ->> 'ParentalSalutation' as ParentalSalutation,
       jsonb_array_elements(Students) ->> 'PartTime' as PartTime,
       jsonb_array_elements(Students) ->> 'PostCode' as PostCode,
       jsonb_array_elements(Students) ->> 'PupilPremium' as PupilPremium,
       jsonb_array_elements(Students) ->> 'ReasonForLeaving' as ReasonForLeaving,
       jsonb_array_elements(Students) ->> 'RegGroup' as RegGroup,
       jsonb_array_elements(Students) ->> 'RegGroupId' as RegGroupId,
       jsonb_array_elements(Students) ->> 'Religion' as Religion,
       jsonb_array_elements(Students) ->> 'ReligionCode' as ReligionCode,
       jsonb_array_elements(Students) ->> 'RowHash' as RowHash,
       jsonb_array_elements(Students) ->> 'SENProvision' as SENProvision,
       jsonb_array_elements(Students) ->> 'ServiceChild' as ServiceChild,
       jsonb_array_elements(Students) ->> 'ServiceChildSource' as ServiceChildSource,
       jsonb_array_elements(Students) ->> 'StandardYearGroupCode' as StandardYearGroupCode,
       jsonb_array_elements(Students) ->> 'StandardYearGroupName' as StandardYearGroupName,
       jsonb_array_elements(Students) ->> 'Street' as Street,
       jsonb_array_elements(Students) ->> 'StudentStatus' as StudentStatus,
       jsonb_array_elements(Students) ->> 'Surname' as Surname,
       jsonb_array_elements(Students) ->> 'TownOrCity' as TownOrCity,
       jsonb_array_elements(Students) ->> 'TravellerSource' as TravellerSource,
       jsonb_array_elements(Students) ->> 'UPN' as UPN,
       jsonb_array_elements(Students) ->> 'UniformAllowance' as UniformAllowance,
       jsonb_array_elements(Students) ->> 'UniqueLearnerNumber' as UniqueLearnerNumber,
       jsonb_array_elements(Students) ->> 'WorkEmail' as WorkEmail,
       jsonb_array_elements(Students) ->> 'XID' as XID,
       jsonb_array_elements(Students) ->> 'YSSA' as YSSA,
       jsonb_array_elements(Students) ->> 'YearGroup' as YearGroup,
       jsonb_array_elements(Students) ->> 'YearGroupId' as YearGroupId,
       jsonb_array_elements(Students) ->> 'YearTaughtIn' as YearTaughtIn,
       jsonb_array_elements(Students) ->> 'formerUPN' as formerUPN,
       'Sample File'
       from
(select j -> 'Students' as Students from students_load) dt1

select jsonb_array_elements(meta) ->> 'DateTime' as DateTime,
       jsonb_array_elements(meta) ->> 'Id' as Id,
       jsonb_array_elements(meta) ->> 'MIS' as MIS,
       jsonb_array_elements(meta) ->> 'Version' as Version,
       'Sample File'
       from
(select j -> 'meta' as meta from students_load) dt1
;